import threading
import time
from http.server import HTTPServer

import requests

from app import backend_server


def _start_server(port: int) -> tuple[HTTPServer, threading.Thread]:
    server = HTTPServer(("127.0.0.1", port), backend_server.Handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    return server, thread


def _rpc(port: int, action: str, data: dict | None = None) -> dict:
    resp = requests.post(
        f"http://127.0.0.1:{port}/rpc",
        json={"action": action, "data": data or {}},
        timeout=10,
    )
    resp.raise_for_status()
    payload = resp.json()
    assert payload.get("ok"), payload
    return payload["data"]


def test_state_and_mock_generation_smoke():
    port = 9876
    server, thread = _start_server(port)
    try:
        state = _rpc(port, "state")
        assert state["session"]["global_settings"]["provider_id"] == "mock"

        add_res = _rpc(port, "add_rows", {"prompts": ["smoke prompt"]})
        row_id = add_res["rows"][-1]["id"]

        _rpc(port, "generate_rows", {"row_ids": [row_id]})

        deadline = time.time() + 10
        last_row = None
        while time.time() < deadline:
            state = _rpc(port, "state")
            last_row = next(r for r in state["session"]["rows"] if r["id"] == row_id)
            if last_row["status"] == "Completed" and last_row["images"]:
                break
            time.sleep(0.1)

        assert last_row is not None
        assert last_row["status"] == "Completed", f"status={last_row['status']}"
        assert last_row["images"], "no images generated by mock provider"
    finally:
        server.shutdown()
        thread.join(timeout=2)
